[package]
name = "risc0-sha256-backend-smoke"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "risc0-sha256-backend-smoke"

[features]
cuda = ["risc0-zkvm/cuda"]

[dependencies]
anyhow = "1"
serde = "1"
methods = { package = "risc0-sha256-backend-smoke-methods", path = "../methods" }
risc0-zkvm = { version = "^3.0.4", features = ["prove"] }
