[package]
name = "risc0-sha256-resolve-smoke"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "risc0-sha256-resolve-smoke"

[features]
cuda = ["risc0-zkvm/cuda"]

[dependencies]
methods = { package = "risc0-sha256-resolve-methods", path = "../methods" }
risc0-zkvm = { version = "^3.0.4", features = ["prove"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
