#!/usr/bin/env python3
"""Package adaptive programs separately; leave both legacy archives byte-for-byte unchanged."""
import argparse
import hashlib
import json
from pathlib import Path
import zipfile


def main():
    """Build a reproducible archive and record the smallest safe domain for every program."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("generated", type=Path)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    crate = root / "vendor/risc0_sha256_backend/crates/risc0-circuit-recursion"
    names = [f"identity_sha256_adaptive_{p}.zkr" for p in range(19, 22)]
    names += [f"{op}_sha256_adaptive_{p}_{q}.zkr" for op in ("join", "resolve", "union") for p in range(19, 22) for q in range(19, 22)]
    rows = {}
    archive = crate / "src/recursion_zkr_sha256_adaptive.zip"
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for name in sorted(names):
            data = (args.generated / name).read_bytes()
            assert data and len(data) % (4 * 23) == 0, name
            rows[name] = len(data) // (4 * 23)
            entry = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(entry, data)
    with zipfile.ZipFile(crate / "src/recursion_zkr_sha256.zip") as z:
        for p in range(14, 25):
            name = f"lift_rv32im_v2_sha256_{p}.zkr"
            size = z.getinfo(name).file_size
            assert size % (4 * 23) == 0
            rows[name] = size // (4 * 23)
    specs = [(name, (count + 1024 - 1).bit_length()) for name, count in sorted(rows.items())]
    assert all(19 <= po2 <= 21 for _, po2 in specs)
    source = "// Generated by tools/zkr-generator/pack_adaptive_zkrs.py.\n"
    source += "/// Program names and minimum power-of-two domains, including 1024 ZK rows.\n"
    source += "pub const SHA256_ADAPTIVE_SPECS: &[(&str, usize)] = &[\n"
    source += "".join(f'    ("{name}", {po2}),\n' for name, po2 in specs)
    source += "];\n\ninclude!(\"adaptive_control_ids.rs\");\n"
    (crate / "src/adaptive.rs").write_text(source)
    # Generation is deliberately two-stage: IDs must be recomputed before using the new bundle.
    (crate / "src/adaptive_control_ids.rs").write_text("pub const SHA256_ADAPTIVE_PROGRAMS: &[(&str, usize, risc0_zkp::core::digest::Digest)] = &[];\n")
    manifest = [{"program": n, "rows": rows[n], "po2": p} for n, p in specs]
    (root / "tools/zkr-generator/adaptive_programs.json").write_text(json.dumps(manifest, indent=2) + "\n")
    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    (crate / "src/recursion_zkr_sha256_adaptive.sha256").write_text(digest + "\n")
    print(f"adaptive_programs={len(specs)} archive_programs={len(names)} archive_sha256={digest}")


if __name__ == "__main__":
    main()
